version: '3'
services:
  glitch:
    image: fishnet/glitch
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      HTTP_PORT: "80"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - node_modules:/var/www/node_modules

volumes:
    node_modules:
        driver: local
