version: '3'
services:

  #PHP Service
  danger:
    image: fishnet/danger
    container_name: danger-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - ./.env
    volumes:
      - ./:/var/www
      - ./config/php.ini:/usr/local/etc/php/conf.d/settings.ini
    networks:
      - danger-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: danger-nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - ./:/var/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - danger-network
    depends_on:
      - db
      - danger

  # MySQL Service
  db:
    image: mariadb
    container_name: danger-mysql
    restart: unless-stopped
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE 
      MYSQL_USER: $DB_USERNAME 
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    networks:
      - danger-network

#Docker Networks
networks:
  danger-network:
    driver: bridge

#Volumes
volumes:
    dbdata:
      driver: local
    node_modules:
      driver: local
