version: '3'
services:

  #PHP+Nginx Service
  app:
    image: fishnet/wiki
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - ./.env
    environment: 
      SITE_URL: $SITE_URL
    volumes:
      - .:/var/www
      - node_modules:/var/www/src/node_modules
      - ./config/php.ini:/usr/local/etc/php/conf.d/settings.ini
      - ./config/config.php:/var/www/src/config.php
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "80:8080"

  # MySQL Service
  db:
    image: mariadb
    restart: unless-stopped
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE 
      MYSQL_USER: $DB_USERNAME 
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./src/schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
    dbdata:
      driver: local
    node_modules:
      driver: local
